BizonaRegistrs/Models/NewParticipantsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BizonaRegistrs.Models
{
    public class NewParticipantsModel
    {
        [Required]
        [StringLength(50, ErrorMessage = "Nav ievadīts vārds!")]
        [Display(Name = "Vārds:")]
        public string parName { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Nav ievadīts uzvārds!")]
        [Display(Name = "Uzvārds:")]
        public string parSurname { get; set; }

        [Required(ErrorMessage = "Nav ievadīts dzimšanas gads!")]
        [Display(Name = "Dzimšanas gads:")]
        public DateTime parBirthDate { get; set; }

        [Required(ErrorMessage = "Izvēlies dzimumu!")]
        [Display(Name = "Dzimums:")]
        public string parGender { get; set; }

        [Required(ErrorMessage = "Nav ievadīts dalības numurs!")]
        [Display(Name = "Dalības numurs:")]
        public int parNumber { get; set; }


        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "1. posma laiks:")]
        public int parRaceTime1 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "2. posma laiks:")]
        public int parRaceTime2 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "3. posma laiks:")]
        public int parRaceTime3 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "4. posma laiks:")]
        public int parRaceTime4 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "5. posma laiks:")]
        public int parRaceTime5 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "6. posma laiks:")]
        public int parRaceTime6 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "7. posma laiks:")]
        public int parRaceTime7 { get; set; }

        [Required(ErrorMessage = "Nav ievadīts laiks!")]
        [Display(Name = "8. posma laiks:")]
        public int parRaceTime8 { get; set; }
    }
}

BizonaRegistrs/Models/ParticipantsResultsModel.cs
using Logic.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BizonaRegistrs.Models
{
    public class ParticipantsResultsModel
    {
        public List<ParticipantsData> Participants;

        public List<ParticipantsData> Participants1;

        public List<ParticipantsData> Participants2;

        public List<ParticipantsData> Participants3;

        public List<ParticipantsData> Participants4;

        public List<ParticipantsData> Participants5;

        public List<ParticipantsData> Participants6;

        public List<ParticipantsData> Participants7;

        public List<ParticipantsData> Participants8;

        public ParticipantsData ActiveParticipant;

        public List<string> ageGroupList;

        [Display(Name = "Izvēlies:")]
        public string choice { get; set; }

        public int place { get; set; }
    }
}

BizonaRegistrs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BizonaRegistrs.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BizonaRegistrs/Controllers/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BizonaRegistrs.Models;
using Logic;

namespace BizonaRegistrs.Controllers
{
    public class ParticipantsController : Controller
    {
        ParticipantsManager manager = new ParticipantsManager();
        ResultsManager resultsManager = new ResultsManager();
        
        // GET: Participants
        public ActionResult Index()
        {
            NewParticipantsModel model = new NewParticipantsModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(NewParticipantsModel model)
        {
            if (ModelState.IsValid)
            {
                AgeGroupManager ageGroupManager = new AgeGroupManager();
                int parBirthYear = model.parBirthDate.Year;
                string parAgeGroup = ageGroupManager.GetParAgeGroup(parBirthYear, model.parGender);

                manager.CreateNewParticipant(
                    model.parName, 
                    model.parSurname, 
                    model.parNumber, 
                    parAgeGroup, 
                    model.parRaceTime1,
                    model.parRaceTime2,
                    model.parRaceTime3,
                    model.parRaceTime4,
                    model.parRaceTime5,
                    model.parRaceTime6,
                    model.parRaceTime7,
                    model.parRaceTime8);

                TempData["Success"] = "Dalībnieks un rezultāts ir reģistrēti!";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Results()
        {
            ParticipantsResultsModel model = new ParticipantsResultsModel();
            PointsManager pointsManager = new PointsManager();
            pointsManager.UpdateParPoints();

            AgeGroupManager ageGroupManager = new AgeGroupManager();
            model.ageGroupList = ageGroupManager.GetAgeGroupList();

            model.choice = "Sum";
            model.Participants = resultsManager.SelectAllParticipants();

            return View(model);
        }

        [HttpPost]
        public ActionResult Results(ParticipantsResultsModel model)
        {
            if (model.choice == "1" ||
                model.choice == "2" ||
                model.choice == "3" ||
                model.choice == "4" ||
                model.choice == "5" ||
                model.choice == "6" ||
                model.choice == "7" ||
                model.choice == "8") { RedirectToAction("Results"); }

            AgeGroupManager ageGroupManager = new AgeGroupManager();
            model.ageGroupList = ageGroupManager.GetAgeGroupList();

            model.Participants = resultsManager.SelectAllParticipants();
            model.Participants1 = resultsManager.SelectAllParticipantsForStage1();
            model.Participants2 = resultsManager.SelectAllParticipantsForStage2();
            model.Participants3 = resultsManager.SelectAllParticipantsForStage3();
            model.Participants4 = resultsManager.SelectAllParticipantsForStage4();
            model.Participants5 = resultsManager.SelectAllParticipantsForStage5();
            model.Participants6 = resultsManager.SelectAllParticipantsForStage6();
            model.Participants7 = resultsManager.SelectAllParticipantsForStage7();
            model.Participants8 = resultsManager.SelectAllParticipantsForStage8();

            return View(model);
        }
    }
}

BizonaRegistrs/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BizonaRegistrs/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BizonaRegistrs/Views/Participants/Index.cshtml
@model BizonaRegistrs.Models.NewParticipantsModel
@{
    ViewBag.Title = "Dalībnieku pievienošana";
}

@using (Html.BeginForm("Index", "Participants", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <h2>Pievienot dalībnieku</h2>

    <br>

    if (TempData["Success"] != null)
    {
        <div>
            <div class="alert alert-success" role="alert">@TempData["Success"]</div>
        </div>
    }

    <div class="form-group">
        @Html.LabelFor(m => m.parName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parSurname, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parSurname, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parBirthDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parBirthDate, new { @type = "date", @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.parGender, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.parGender, new List<SelectListItem>{
                new SelectListItem{ Text="Vīrietis", Value="Male"},
                new SelectListItem{ Text="Sieviete", Value="Female"}
            }, "-- Izvēlies --", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.parNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime1, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime1, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime2, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime2, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime3, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime3, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime4, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime4, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime5, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime5, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime6, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime6, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime7, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime7, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.parRaceTime8, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.parRaceTime8, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" padding="top:20px">
            <input type="submit" class="btn btn-default" value="Pievienot dalībnieku" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BizonaRegistrs/Views/Participants/Results.cshtml
@model BizonaRegistrs.Models.ParticipantsResultsModel
@{
    ViewBag.Title = "Rezultāti";
}

@using (Html.BeginForm("Results", "Participants", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    <h2>Rezultāti</h2>

    <br>

    <div class="form-group">
        @Html.LabelFor(m => m.choice, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.choice, new List<SelectListItem>{
                new SelectListItem{ Text="Kopvērtējums", Value="Sum"},
                new SelectListItem{ Text="1. posms", Value="1"},
                new SelectListItem{ Text="2. posms", Value="2"},
                new SelectListItem{ Text="3. posms", Value="3"},
                new SelectListItem{ Text="4. posms", Value="4"},
                new SelectListItem{ Text="5. posms", Value="5"},
                new SelectListItem{ Text="6. posms", Value="6"},
                new SelectListItem{ Text="7. posms", Value="7"},
                new SelectListItem{ Text="8. posms", Value="8"}
            }, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" padding="top:20px">
            <input type="submit" class="btn btn-default" value="Apstiprināt" />
        </div>
    </div>

    <br>

    if (Model.choice == "Sum")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>Punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parPointsSum</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "1")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>1. posma laiks</th>
                <th>1. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants1)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime1</td>
                            <td>@participant.parPoints1</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "2")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>2. posma laiks</th>
                <th>2. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants2)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime2</td>
                            <td>@participant.parPoints2</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "3")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>3. posma laiks</th>
                <th>3. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants3)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime3</td>
                            <td>@participant.parPoints3</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "4")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>4. posma laiks</th>
                <th>4. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants4)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime4</td>
                            <td>@participant.parPoints4</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "5")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>5. posma laiks</th>
                <th>5. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants5)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime5</td>
                            <td>@participant.parPoints5</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "6")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>6. posma laiks</th>
                <th>6. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants6)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime6</td>
                            <td>@participant.parPoints6</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "7")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>7. posma laiks</th>
                <th>7. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants7)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime7</td>
                            <td>@participant.parPoints7</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }

    if (Model.choice == "8")
    {
        <table class="table table-hover table-striped">
            <tr>
                <th>#</th>
                <th>Vecuma grupa</th>
                <th>Numurs</th>
                <th>Vārds</th>
                <th>Uzvārds</th>
                <th>8. posma laiks</th>
                <th>8. posma punkti</th>
            </tr>
            @foreach (var ageGroup in Model.ageGroupList)
            {
                Model.place = 1;
                foreach (var participant in Model.Participants8)
                {
                    if (ageGroup.ToString() == participant.parAgeGroup)
                    {
                        <tr>
                            <td>@Model.place</td>
                            <td>@ageGroup</td>
                            <td>@participant.parNumber</td>
                            <td>@participant.parName</td>
                            <td>@participant.parSurname</td>
                            <td>@participant.parRaceTime8</td>
                            <td>@participant.parPoints8</td>
                        </tr>
                        Model.place++;
                    }
                }
            }
        </table>
    }
}

BizonaRegistrs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bizona reģistrs", "Index", "Participants", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dalībnieku pievienošana", "Index", "Participants")</li>
                    <li>@Html.ActionLink("Rezultāti", "Results", "Participants")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Made by Artūrs Hasanovs</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>